# Generated by Django 4.2.18 on 2025-04-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0717_errortrackingassignmentrule_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdefinition",
            name="required_properties",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
